// <auto-generated />
using System;
using CostingTool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CostingTool.Data.Migrations
{
    [DbContext(typeof(CostingDbContext))]
    partial class CostingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CostingTool.Engine.MethodConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursPerDay")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IndirectCostRecovery")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineAvailabilityBasis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MachineAvailableDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MidpointRule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RateDecimals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffAvailabilityBasis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StaffAvailableDays")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("MethodConfigs");
                });

            modelBuilder.Entity("CostingTool.Models.AppNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientUserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RicCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserName", "IsRead");

                    b.ToTable("AppNotifications");
                });

            modelBuilder.Entity("CostingTool.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PasswordChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CostingTool.Models.RicCapability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AboveCapacityReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapacityBaseline")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ForecastApfrUse")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ForecastCommercialUse")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ForecastUwaUse")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStaffReliant")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaximumCapacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProposedApfrRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProposedCommercialRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProposedUwaRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RicCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StaffFte")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StatedBaseline")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatedBaselineNote")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RicCycleId");

                    b.ToTable("RicCapabilities");
                });

            modelBuilder.Entity("CostingTool.Models.RicCapacityDeduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RicCapabilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RicCapabilityId");

                    b.ToTable("RicCapacityDeductions");
                });

            modelBuilder.Entity("CostingTool.Models.RicCostEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FellowshipType")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FloorArea")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FloorAreaRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("FundingType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PercentWorked")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonnelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RicCapabilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RicCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalaryScale")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryStep")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffType")
                        .HasColumnType("TEXT");

                    b.Property<string>("StepOption")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperannuationPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RicCapabilityId");

                    b.HasIndex("RicCycleId");

                    b.ToTable("RicCostEntries");
                });

            modelBuilder.Entity("CostingTool.Models.RicCostYearAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RicCostEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RicCostEntryId");

                    b.ToTable("RicCostYearAmounts");
                });

            modelBuilder.Entity("CostingTool.Models.RicCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("BenchmarkNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillableUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("CostingAssumptions")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastEditedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastEditedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastEditedByDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LastStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MethodVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PricingJustification")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SealedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SealedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupersedesCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UtilisationAssumptions")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SupersedesCycleId");

                    b.ToTable("RicCycles");
                });

            modelBuilder.Entity("CostingTool.Models.RicCapability", b =>
                {
                    b.HasOne("CostingTool.Models.RicCycle", "RicCycle")
                        .WithMany("Capabilities")
                        .HasForeignKey("RicCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RicCycle");
                });

            modelBuilder.Entity("CostingTool.Models.RicCapacityDeduction", b =>
                {
                    b.HasOne("CostingTool.Models.RicCapability", "RicCapability")
                        .WithMany("CapacityDeductions")
                        .HasForeignKey("RicCapabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RicCapability");
                });

            modelBuilder.Entity("CostingTool.Models.RicCostEntry", b =>
                {
                    b.HasOne("CostingTool.Models.RicCapability", "Capability")
                        .WithMany()
                        .HasForeignKey("RicCapabilityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CostingTool.Models.RicCycle", "RicCycle")
                        .WithMany("Costs")
                        .HasForeignKey("RicCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capability");
                    b.Navigation("RicCycle");
                });

            modelBuilder.Entity("CostingTool.Models.RicCostYearAmount", b =>
                {
                    b.HasOne("CostingTool.Models.RicCostEntry", "RicCostEntry")
                        .WithMany("YearAmounts")
                        .HasForeignKey("RicCostEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RicCostEntry");
                });

            modelBuilder.Entity("CostingTool.Models.RicCycle", b =>
                {
                    b.HasOne("CostingTool.Models.RicCycle", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("CostingTool.Models.RicCapability", b =>
                {
                    b.Navigation("CapacityDeductions");
                });

            modelBuilder.Entity("CostingTool.Models.RicCostEntry", b =>
                {
                    b.Navigation("YearAmounts");
                });

            modelBuilder.Entity("CostingTool.Models.RicCycle", b =>
                {
                    b.Navigation("Capabilities");
                    b.Navigation("Costs");
                });
#pragma warning restore 612, 618
        }
    }
}
